### ISSUE TITLE
[1.12] Crashes when connecting to server

### ISSUE THREAD

**Issue by Jomik** [univrsal/IIDY#1]
[crash-2017-11-28_12.38.11-client.txt](https://github.com/univrsal/IIDY/files/1509702/crash-2017-11-28_12.38.11-client.txt)
IIDY isn't on the server, as that caused the server to crash :D

**Comment by univrsal** [comment]
i'm on it

**Comment by Jomik** [comment]
I wasn't sure if this is a client only mod or a server side mod as well. If it's for both sides, then there is also an issue trying to run it on a server.

**Comment by univrsal** [comment]
yeah I fixed the crash on serverstartup but there's still some issues when running it on a dedicated server.
Also it's not a client side only mod. I wanted it to be, but the client has no information about tile entities until the server sends them (e.g. when opening a gui)

**Comment by univrsal** [comment]
Alright I fixed the issues that prevented iidy from working on dedicated servers. I'll fix some other minor issues and make a new release, thanks for reporting!
