### ISSUE TITLE
Server Crash on Join

### ISSUE THREAD

**Issue by maxlowry123** [univrsal/IIDY#2]
I was just testing the mod for the first time. I told it to get the block state of a dirt block and notify me when it was air. I then broke it, and the server crashed and keeps crashing every time I join the server. 
Crash Log: [https://pastebin.com/ynWB7HK6](https://pastebin.com/ynWB7HK6)
I had to remove the mod before I could get back on to the server.

**Comment by univrsal** [comment]
Ugh, I used chat formatting which isn't available on the server side so it crashes.
Should be fixed soon.
